version: "2"
run:
  tests: false
linters-settings:
  goimports:
    local-prefixes: github.com/p2p-VPN/member
    format-only: false
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - gocheckcompilerdirectives
    - gochecksumtype
    - goconst
    - gocritic
    - gosec
    - gosmopolitan
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - noctx
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - revive
    - rowserrcheck
    - spancheck
    - sqlclosecheck
    - testifylint
    - unconvert
    - unparam
    - whitespace
    - zerologlint
  settings:
    govet:
      enable-all: true
      disable:
        - printf
        - fieldalignment
        - shadow
    prealloc:
      simple: false
    revive:
      severity: error
      rules:
        - name: bare-return
        - name: bool-literal-in-expr
        - name: call-to-gc
        - name: error-return
        - name: error-strings
        - name: error-naming
        - name: if-return
        - name: increment-decrement
        - name: var-declaration
        - name: var-naming
        - name: dot-imports
        - name: package-comments
        - name: range
        - name: struct-tag
        - name: string-of-int
        - name: redefines-builtin-id
        - name: range-val-in-closure
        - name: range-val-address
        - name: receiver-naming
        - name: time-equal
        - name: time-naming
        - name: unexported-return
        - name: exported
        - name: indent-error-flow
        - name: errorf
        - name: unexported-naming
        - name: unconditional-recursion
        - name: empty-lines
        - name: empty-block
        - name: waitgroup-by-value
        - name: constant-logical-expr
        - name: superfluous-else
        - name: datarace
        - name: defer
        - name: optimize-operands-order
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: nested-structs
        - name: identical-branches
        - name: early-return
        - name: deep-exit
        - name: cyclomatic
          arguments:
            - 30
        - name: atomic
        - name: function-result-limit
          arguments:
            - 3
        - name: unnecessary-stmt
        - name: unreachable-code
    staticcheck:
      checks:
        - all
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - revive
        source: '^//go:generate '
      - linters:
          - dupl
          - errcheck
          - gocyclo
          - gosec
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$