// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package httpclient

import (
	"context"
	"net/http"
	"net/url"
	"sync"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			DoFunc: func(ctx context.Context, method string, urlMoqParam *url.URL, opts ...RequestOptions[any]) (*Response, error) {
//				panic("mock out the Do method")
//			},
//			DoRequestFunc: func(ctx context.Context, req *http.Request) (*Response, error) {
//				panic("mock out the DoRequest method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// DoFunc mocks the Do method.
	DoFunc func(ctx context.Context, method string, urlMoqParam *url.URL, opts ...RequestOptions[any]) (*Response, error)

	// DoRequestFunc mocks the DoRequest method.
	DoRequestFunc func(ctx context.Context, req *http.Request) (*Response, error)

	// calls tracks calls to the methods.
	calls struct {
		// Do holds details about calls to the Do method.
		Do []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Method is the method argument value.
			Method string
			// UrlMoqParam is the urlMoqParam argument value.
			UrlMoqParam *url.URL
			// Opts is the opts argument value.
			Opts []RequestOptions[any]
		}
		// DoRequest holds details about calls to the DoRequest method.
		DoRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Req is the req argument value.
			Req *http.Request
		}
	}
	lockDo        sync.RWMutex
	lockDoRequest sync.RWMutex
}

// Do calls DoFunc.
func (mock *ClientMock) Do(ctx context.Context, method string, urlMoqParam *url.URL, opts ...RequestOptions[any]) (*Response, error) {
	if mock.DoFunc == nil {
		panic("ClientMock.DoFunc: method is nil but Client.Do was just called")
	}
	callInfo := struct {
		Ctx         context.Context
		Method      string
		UrlMoqParam *url.URL
		Opts        []RequestOptions[any]
	}{
		Ctx:         ctx,
		Method:      method,
		UrlMoqParam: urlMoqParam,
		Opts:        opts,
	}
	mock.lockDo.Lock()
	mock.calls.Do = append(mock.calls.Do, callInfo)
	mock.lockDo.Unlock()
	return mock.DoFunc(ctx, method, urlMoqParam, opts...)
}

// DoCalls gets all the calls that were made to Do.
// Check the length with:
//
//	len(mockedClient.DoCalls())
func (mock *ClientMock) DoCalls() []struct {
	Ctx         context.Context
	Method      string
	UrlMoqParam *url.URL
	Opts        []RequestOptions[any]
} {
	var calls []struct {
		Ctx         context.Context
		Method      string
		UrlMoqParam *url.URL
		Opts        []RequestOptions[any]
	}
	mock.lockDo.RLock()
	calls = mock.calls.Do
	mock.lockDo.RUnlock()
	return calls
}

// DoRequest calls DoRequestFunc.
func (mock *ClientMock) DoRequest(ctx context.Context, req *http.Request) (*Response, error) {
	if mock.DoRequestFunc == nil {
		panic("ClientMock.DoRequestFunc: method is nil but Client.DoRequest was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Req *http.Request
	}{
		Ctx: ctx,
		Req: req,
	}
	mock.lockDoRequest.Lock()
	mock.calls.DoRequest = append(mock.calls.DoRequest, callInfo)
	mock.lockDoRequest.Unlock()
	return mock.DoRequestFunc(ctx, req)
}

// DoRequestCalls gets all the calls that were made to DoRequest.
// Check the length with:
//
//	len(mockedClient.DoRequestCalls())
func (mock *ClientMock) DoRequestCalls() []struct {
	Ctx context.Context
	Req *http.Request
} {
	var calls []struct {
		Ctx context.Context
		Req *http.Request
	}
	mock.lockDoRequest.RLock()
	calls = mock.calls.DoRequest
	mock.lockDoRequest.RUnlock()
	return calls
}
