version: "2"
run:
  timeout: 10m
  relative-path-mode: gomod
  concurrency: 4
linters:
  default: none
  enable:
    - asciicheck
    - bidichk
    - bodyclose
    - canonicalheader
    - copyloopvar
    - decorder
    - dupl
    - dupword
    - durationcheck
    - embeddedstructfieldcheck
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - exhaustive
    - exptostd
    - fatcontext
    - forbidigo
    - forcetypeassert
    - funlen
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - godox
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - iface
    - ineffassign
    - lll
    - mirror
    - misspell
    - mnd
    - modernize
    - musttag
    - nestif
    - nilerr
    - nilnesserr
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - nosprintfhostport
    - prealloc
    - predeclared
    - protogetter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - tagalign
    - thelper
    - unconvert
    - unparam
    - unused
    - usestdlibvars
    - usetesting
    - wastedassign
    - whitespace
    - zerologlint
    - dogsled
    - nakedret
    - noctx
    - staticcheck
  settings:
    grouper:
      const-require-grouping: true
      import-require-single-import: true
    godox:
      keywords:
        - FIXME
        - BUG
    errcheck:
      check-type-assertions: true
      check-blank: false
      disable-default-exclusions: false
      verbose: true
    decorder:
      dec-order:
        - type
        - const
        - var
        - func
    dupl:
      threshold: 100
    funlen:
      lines: 100
      statements: 50
    lll:
      line-length: 140
    misspell:
      locale: US
      ignore-rules:
        - cancelled
    nlreturn:
      block-size: 2
    goconst:
      min-len: 2
      min-occurrences: 3
    gocritic:
      disabled-checks:
        - dupImport
        - ifElseChain
        - octalLiteral
        - whyNoLint
      enabled-tags:
        - diagnostic
        - experimental
        - opinionated
        - style
    gocyclo:
      min-complexity: 15
    gosec:
      excludes:
        - G115
    govet:
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    mnd:
      checks:
        - argument
        - case
        - condition
        - return
      ignored-numbers:
        - "0"
        - "1"
        - "2"
        - "3"
      ignored-functions:
        - strings.SplitN
    nolintlint:
      require-explanation: false
      require-specific: false
      allow-unused: false
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - funlen
          - goconst
          - gocritic
          - gosec
          - lll
          - mnd
          - staticcheck
          - forbidigo
          - decorder
          - dupl
          - dupword
        path: _test\.go
      - linters:
          - dupl
          - funlen
          - goconst
          - gocritic
          - gosec
          - lll
          - mnd
          - staticcheck
          - forbidigo
          - decorder
          - dupl
          - dupword
        path: test/
      - linters:
          - dupl
          - gochecknoinits
        path: migrations/
      - path: pkg/golinters/errcheck.go
        text: 'SA1019: errCfg.Exclude is deprecated: use ExcludeFunctions instead'
      - path: pkg/commands/run.go
        text: 'SA1019: lsc.Errcheck.Exclude is deprecated: use ExcludeFunctions instead'
      - path: pkg/commands/run.go
        text: 'SA1019: e.cfg.Run.Deadline is deprecated: Deadline exists for historical compatibility and should not be used.'
      - path: pkg/golinters/gofumpt.go
        text: 'SA1019: settings.LangVersion is deprecated: use the global `run.go` instead.'
      - path: pkg/golinters/staticcheck_common.go
        text: 'SA1019: settings.GoVersion is deprecated: use the global `run.go` instead.'
      - path: pkg/lint/lintersdb/manager.go
        text: 'SA1019: (.+).(GoVersion|LangVersion) is deprecated: use the global `run.go` instead.'
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    goimports:
      local-prefixes:
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$

