// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package redis

import (
	"context"
	"sync"
	"time"
)

// Ensure, that ClientMock does implement Client.
// If this is not the case, regenerate this file with moq.
var _ Client = &ClientMock{}

// ClientMock is a mock implementation of Client.
//
//	func TestSomethingThatUsesClient(t *testing.T) {
//
//		// make and configure a mocked Client
//		mockedClient := &ClientMock{
//			AddFunc: func(ctx context.Context, key string, value []byte, expiration time.Duration) error {
//				panic("mock out the Add method")
//			},
//			DecFunc: func(ctx context.Context, key string) (int64, error) {
//				panic("mock out the Dec method")
//			},
//			DelFunc: func(ctx context.Context, key string)  {
//				panic("mock out the Del method")
//			},
//			GetFunc: func(ctx context.Context, key string) ([]byte, error) {
//				panic("mock out the Get method")
//			},
//			GetIntFunc: func(ctx context.Context, key string) (int64, error) {
//				panic("mock out the GetInt method")
//			},
//			GetValuesByPatternFunc: func(ctx context.Context, pattern string) ([][]byte, error) {
//				panic("mock out the GetValuesByPattern method")
//			},
//		}
//
//		// use mockedClient in code that requires Client
//		// and then make assertions.
//
//	}
type ClientMock struct {
	// AddFunc mocks the Add method.
	AddFunc func(ctx context.Context, key string, value []byte, expiration time.Duration) error

	// DecFunc mocks the Dec method.
	DecFunc func(ctx context.Context, key string) (int64, error)

	// DelFunc mocks the Del method.
	DelFunc func(ctx context.Context, key string)

	// GetFunc mocks the Get method.
	GetFunc func(ctx context.Context, key string) ([]byte, error)

	// GetIntFunc mocks the GetInt method.
	GetIntFunc func(ctx context.Context, key string) (int64, error)

	// GetValuesByPatternFunc mocks the GetValuesByPattern method.
	GetValuesByPatternFunc func(ctx context.Context, pattern string) ([][]byte, error)

	// calls tracks calls to the methods.
	calls struct {
		// Add holds details about calls to the Add method.
		Add []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
			// Value is the value argument value.
			Value []byte
			// Expiration is the expiration argument value.
			Expiration time.Duration
		}
		// Dec holds details about calls to the Dec method.
		Dec []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Del holds details about calls to the Del method.
		Del []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// Get holds details about calls to the Get method.
		Get []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetInt holds details about calls to the GetInt method.
		GetInt []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Key is the key argument value.
			Key string
		}
		// GetValuesByPattern holds details about calls to the GetValuesByPattern method.
		GetValuesByPattern []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Pattern is the pattern argument value.
			Pattern string
		}
	}
	lockAdd                sync.RWMutex
	lockDec                sync.RWMutex
	lockDel                sync.RWMutex
	lockGet                sync.RWMutex
	lockGetInt             sync.RWMutex
	lockGetValuesByPattern sync.RWMutex
}

// Add calls AddFunc.
func (mock *ClientMock) Add(ctx context.Context, key string, value []byte, expiration time.Duration) error {
	if mock.AddFunc == nil {
		panic("ClientMock.AddFunc: method is nil but Client.Add was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		Key        string
		Value      []byte
		Expiration time.Duration
	}{
		Ctx:        ctx,
		Key:        key,
		Value:      value,
		Expiration: expiration,
	}
	mock.lockAdd.Lock()
	mock.calls.Add = append(mock.calls.Add, callInfo)
	mock.lockAdd.Unlock()
	return mock.AddFunc(ctx, key, value, expiration)
}

// AddCalls gets all the calls that were made to Add.
// Check the length with:
//
//	len(mockedClient.AddCalls())
func (mock *ClientMock) AddCalls() []struct {
	Ctx        context.Context
	Key        string
	Value      []byte
	Expiration time.Duration
} {
	var calls []struct {
		Ctx        context.Context
		Key        string
		Value      []byte
		Expiration time.Duration
	}
	mock.lockAdd.RLock()
	calls = mock.calls.Add
	mock.lockAdd.RUnlock()
	return calls
}

// Dec calls DecFunc.
func (mock *ClientMock) Dec(ctx context.Context, key string) (int64, error) {
	if mock.DecFunc == nil {
		panic("ClientMock.DecFunc: method is nil but Client.Dec was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDec.Lock()
	mock.calls.Dec = append(mock.calls.Dec, callInfo)
	mock.lockDec.Unlock()
	return mock.DecFunc(ctx, key)
}

// DecCalls gets all the calls that were made to Dec.
// Check the length with:
//
//	len(mockedClient.DecCalls())
func (mock *ClientMock) DecCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDec.RLock()
	calls = mock.calls.Dec
	mock.lockDec.RUnlock()
	return calls
}

// Del calls DelFunc.
func (mock *ClientMock) Del(ctx context.Context, key string) {
	if mock.DelFunc == nil {
		panic("ClientMock.DelFunc: method is nil but Client.Del was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockDel.Lock()
	mock.calls.Del = append(mock.calls.Del, callInfo)
	mock.lockDel.Unlock()
	mock.DelFunc(ctx, key)
}

// DelCalls gets all the calls that were made to Del.
// Check the length with:
//
//	len(mockedClient.DelCalls())
func (mock *ClientMock) DelCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockDel.RLock()
	calls = mock.calls.Del
	mock.lockDel.RUnlock()
	return calls
}

// Get calls GetFunc.
func (mock *ClientMock) Get(ctx context.Context, key string) ([]byte, error) {
	if mock.GetFunc == nil {
		panic("ClientMock.GetFunc: method is nil but Client.Get was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGet.Lock()
	mock.calls.Get = append(mock.calls.Get, callInfo)
	mock.lockGet.Unlock()
	return mock.GetFunc(ctx, key)
}

// GetCalls gets all the calls that were made to Get.
// Check the length with:
//
//	len(mockedClient.GetCalls())
func (mock *ClientMock) GetCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGet.RLock()
	calls = mock.calls.Get
	mock.lockGet.RUnlock()
	return calls
}

// GetInt calls GetIntFunc.
func (mock *ClientMock) GetInt(ctx context.Context, key string) (int64, error) {
	if mock.GetIntFunc == nil {
		panic("ClientMock.GetIntFunc: method is nil but Client.GetInt was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Key string
	}{
		Ctx: ctx,
		Key: key,
	}
	mock.lockGetInt.Lock()
	mock.calls.GetInt = append(mock.calls.GetInt, callInfo)
	mock.lockGetInt.Unlock()
	return mock.GetIntFunc(ctx, key)
}

// GetIntCalls gets all the calls that were made to GetInt.
// Check the length with:
//
//	len(mockedClient.GetIntCalls())
func (mock *ClientMock) GetIntCalls() []struct {
	Ctx context.Context
	Key string
} {
	var calls []struct {
		Ctx context.Context
		Key string
	}
	mock.lockGetInt.RLock()
	calls = mock.calls.GetInt
	mock.lockGetInt.RUnlock()
	return calls
}

// GetValuesByPattern calls GetValuesByPatternFunc.
func (mock *ClientMock) GetValuesByPattern(ctx context.Context, pattern string) ([][]byte, error) {
	if mock.GetValuesByPatternFunc == nil {
		panic("ClientMock.GetValuesByPatternFunc: method is nil but Client.GetValuesByPattern was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Pattern string
	}{
		Ctx:     ctx,
		Pattern: pattern,
	}
	mock.lockGetValuesByPattern.Lock()
	mock.calls.GetValuesByPattern = append(mock.calls.GetValuesByPattern, callInfo)
	mock.lockGetValuesByPattern.Unlock()
	return mock.GetValuesByPatternFunc(ctx, pattern)
}

// GetValuesByPatternCalls gets all the calls that were made to GetValuesByPattern.
// Check the length with:
//
//	len(mockedClient.GetValuesByPatternCalls())
func (mock *ClientMock) GetValuesByPatternCalls() []struct {
	Ctx     context.Context
	Pattern string
} {
	var calls []struct {
		Ctx     context.Context
		Pattern string
	}
	mock.lockGetValuesByPattern.RLock()
	calls = mock.calls.GetValuesByPattern
	mock.lockGetValuesByPattern.RUnlock()
	return calls
}
